### PR TITLE
Properly support bytestring-0.11

### LINKED ISSUE #52: bytesting-0.11 breaks on older GHCs.
```
% cabal build -w ghc-7.10.3 --constraint='bytestring >=0.11' --allow-newer=bytestring
```

```
src/Data/Bytes/Serial.hs:291:3:
    Not in scope: data constructor ‘PS’
    Perhaps you meant ‘BS’ (imported from Data.ByteString.Internal)
```

with

```
source-repository-package
  type: git
  location: https://github.com/haskell/text
  tag: v1.2.4.1-rc1
```

CI doesn't test these. They are however easy to spot if you grep for `PS` constructor.

### PR DESCRIPTION
**Pull request by RyanGlScott**
It was pointed out in ekmett/bytes#52 that my patch to allow `bytes` to build with `bytestring-0.11.*` in ed6135e1b59da7b46407d3fdc9b161810bac8baa was incomplete. This is because I overlooked the fact that `bytestring-0.11.*` only exports the `PS` pattern synonym on GHC 8.0 or later, and since `bytes` matches on `PS`, it wouldn't compile if you combined `bytestring-0.11` with a pre-8.0 version of GHC.

I adopted a similar fix as in https://github.com/ekmett/lens/commit/1debced4e9cb8b904b1f52c3ab10a551e40f3b2d#diff-700f6fcfab7d955dd35e76a01956c66b89cff9f681274163b6d60051229ef14dR217 to allow `bytestring-0.11` to be used with all supported versions of GHC.

Fixes #52.

### CODE REVIEW

**Review by phadej — APPROVED** [review]
I tried locally, and `bytes` builds fine with all supported GHCs + `bytestring-0.11`. :+1:
